"""
Django settings for shoppinglist project.

Generated by 'django-admin startproject' using Django 1.8.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&lj5f-1p38tdwl6h^8%yvc78n6l&fto59!r&_-q-g#v8yx73l)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'djangojs',
    'shoppinglist',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'django.middleware.security.SecurityMiddleware',
)


ROOT_URLCONF = 'shoppinglist.urls'

LOGIN_URL = 'home'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            '/Users/danielluker/Workspace/ShoppingList/webapp/public/html',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

TEMPLATE_DIRS = os.path.join(
    '/Users/danielluker/Workspace/ShoppingList/webapp/public/html'
)

WSGI_APPLICATION = 'shoppinglist.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {

        # """ Offline dev """
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': 'db',

        # """ Online dev """
        # 'ENGINE': 'django_mongodb_engine',
        # 'NAME': 'shopping_list',
        # 'USER': 'dluker',
        # 'PASSWORD': 'ekw-kJC-h7Y-Hh2',
        # 'HOST': 'ds053794.mongolab.com',
        # 'PORT': '53794',
        # 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        # 'ENGINE': '',
    }
}

# SESSION_ENGINE = 'mongoengine.django.sessions'
# Mongo DB settings
# import mongoengine
# _MONGODB_USER = 'dluker'
# _MONGODB_PASSWD = 'ekw-kJC-h7Y-Hh2'
# _MONGODB_HOST = 'ds053794.mongolab.com:53794'
# _MONGODB_NAME = 'shopping_list'
# _MONGODB_DATABASE_HOST = \
#     'mongodb://%s:%s@%s/%s' \
#     % (_MONGODB_USER, _MONGODB_PASSWD, _MONGODB_HOST, _MONGODB_NAME)
# mongoengine.connect(_MONGODB_NAME, host=_MONGODB_DATABASE_HOST)
# AUTHENTICATION_BACKENDS = (
#     'mongoengine.django.auth.MongoEngineBackend',
# )

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Chicago'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/Users/danielluker/Workspace/ShoppingList/webapp/public/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    '/Users/danielluker/Workspace/ShoppingList/webapp/public/'
]
